#!/bin/bash
echo "=== FINAL VERIFICATION ==="
echo ""
echo "1. Verbose Log() calls with LogCategory (should be 0):"
count_verbose=$(grep -r "CombatLogger\.Log(" Assets/Scripts/Combat --include="*.cs" | grep -v "CombatLogger.cs" | grep "LogCategory" | wc -l)
echo "   $count_verbose"
echo ""
echo "2. Files using convenience methods:"
count_files=$(grep -rl "CombatLogger\.Log" Assets/Scripts/Combat --include="*.cs" | grep -v "CombatLogger.cs" | wc -l)
echo "   $count_files files"
echo ""
echo "3. Convenience method usage:"
echo "   - LogAI: $(grep -r 'CombatLogger\.LogAI(' Assets/Scripts/Combat --include='*.cs' | grep -v 'CombatLogger.cs' | wc -l) calls"
echo "   - LogCombat: $(grep -r 'CombatLogger\.LogCombat(' Assets/Scripts/Combat --include='*.cs' | grep -v 'CombatLogger.cs' | wc -l) calls"
echo "   - LogSkill: $(grep -r 'CombatLogger\.LogSkill(' Assets/Scripts/Combat --include='*.cs' | grep -v 'CombatLogger.cs' | wc -l) calls"
echo "   - LogMovement: $(grep -r 'CombatLogger\.LogMovement(' Assets/Scripts/Combat --include='*.cs' | grep -v 'CombatLogger.cs' | wc -l) calls"
echo "   - LogWeapon: $(grep -r 'CombatLogger\.LogWeapon(' Assets/Scripts/Combat --include='*.cs' | grep -v 'CombatLogger.cs' | wc -l) calls"
echo "   - LogPattern: $(grep -r 'CombatLogger\.LogPattern(' Assets/Scripts/Combat --include='*.cs' | grep -v 'CombatLogger.cs' | wc -l) calls"
echo "   - LogFormation: $(grep -r 'CombatLogger\.LogFormation(' Assets/Scripts/Combat --include='*.cs' | grep -v 'CombatLogger.cs' | wc -l) calls"
echo "   - LogAttack: $(grep -r 'CombatLogger\.LogAttack(' Assets/Scripts/Combat --include='*.cs' | grep -v 'CombatLogger.cs' | wc -l) calls"
echo "   - LogHealth: $(grep -r 'CombatLogger\.LogHealth(' Assets/Scripts/Combat --include='*.cs' | grep -v 'CombatLogger.cs' | wc -l) calls"
echo "   - LogStamina: $(grep -r 'CombatLogger\.LogStamina(' Assets/Scripts/Combat --include='*.cs' | grep -v 'CombatLogger.cs' | wc -l) calls"
echo "   - LogUI: $(grep -r 'CombatLogger\.LogUI(' Assets/Scripts/Combat --include='*.cs' | grep -v 'CombatLogger.cs' | wc -l) calls"
echo "   - LogSystem: $(grep -r 'CombatLogger\.LogSystem(' Assets/Scripts/Combat --include='*.cs' | grep -v 'CombatLogger.cs' | wc -l) calls"
echo ""
echo "=== VERIFICATION COMPLETE ==="
